aayu/aayu/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include(('books.urls', 'books'), namespace='books')),
    path('', include(('users.urls', 'users'), namespace='users')),
]

aayu/books/urls.py
from django.urls import path

from books.views import BookListView, BookDetailView

urlpatterns = [
    path('', BookListView.as_view(), name='list'),
    path('<int:pk>/', BookDetailView.as_view(), name='detail'),
]

aayu/templates/includes/footer.html
<style>
    .m-footer{
        position: fixed;
        bottom: 0;
        left: 0;
        z-index: 1111;
        width: 100%;
        align-items: center;
        text-align: center;
    }
</style>

<footer class="panel-footer m-footer">
    <div>
        <span class="text-muted">Contact information: <a href="mailto:anish.shrestha@mailinator.com">Anish Shrestha</a>.</span>
    </div>
</footer>

aayu/templates/includes/header.html
{% load static %}
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="http://getbootstrap.com/docs/3.3/favicon.ico">


<script src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous">
</script>

<!-- Bootstrap core CSS -->
<link href="{% static "dashboard_files/bootstrap.css" %}" rel="stylesheet">

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="{% static "dashboard_files/ie10-viewport-bug-workaround.css" %}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="{% static "dashboard_files/dashboard.css" %}" rel="stylesheet">

<!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
<!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
<script src="{% static "dashboard_files/ie-emulation-modes-warning.js" %}"></script>

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

aayu/templates/includes/nav-sidebar.html
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li><a href={% url "users:list" %}>Users</a></li>
    <li><a href={% url "books:list" %}>Books</a></li>
  </ul>
</div>

aayu/templates/includes/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Lorem Ipsum</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href={% url "users:list" %}>Dashboard</a></li>
        <li><a href="/admin/">Admin Site</a></li>
        <li><a href="#">Help</a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form>
    </div>
  </div>
</nav>

aayu/templates/includes/pagination.html
{% if is_paginated %}
    <ul class="pagination">
        <li class="page-item"><a href="?{{ request.GET.urlencode }}&page=1">First</a></li>
        {% if page_obj.has_previous %}
            <li class="page-item"><a href="?{{ request.GET.urlencode }}&page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        <li class="active"><span>{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
        {% if page_obj.has_next %}
            <li class="page-item"><a href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
            <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
        <li class="page-item"><a href="?{{ request.GET.urlencode }}&page={{ paginator.num_pages }}">Last</a></li>
    </ul>
{% endif %}